
language: python

python:
  - "2.7"
  - "3.6"

env:
    global:
        - GH_REF: github.com/samreay/WorkshopExample.git

install:
  - pip install .
  - pip install -r requirements.txt

script:
  - pytest --cov=./ -v

after_success:
  - codecov
  - chmod u+x deploy.sh
  - ./deploy.sh
